<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block Signifyd\Connect\Block\Adminhtml\CaseInfo */ ?>
<?php

if ($block->getCaseEntity()->isEmpty()) {
    return '';
}
?>
<section class="admin__page-section order-case-info">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Fraud Protection Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item case-information">
            <div class="admin__table-wrapper">
                <table class="admin__table-secondary order-case-table">
                    <tbody>
                    <tr>
                        <th class="col-guarantee-disposition"><?= $block->escapeHtml(__('Signifyd Guarantee Decision')) ?></th>
                        <td class="col-guarantee-disposition"><?= $block->escapeHtml($block->getCaseGuaranteeDisposition()) ?></td>
                    </tr>
                    <tr>
                        <th class="col-guarantee-disposition"><?= $block->escapeHtml(__('Signifyd Score')) ?></th>
                        <td class="col-guarantee-disposition"><?= $block->escapeHtml($block->getCaseScore()) ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>